//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayCarrot.RCP.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayCarrot.RCP.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action succeeded.
        /// </summary>
        public static string ActionSucceeded {
            get {
                return ResourceManager.GetString("ActionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Error message: {1}.
        /// </summary>
        public static string App_ExceptionMessage {
            get {
                return ResourceManager.GetString("App_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string App_ExceptionMessageDefaultHeader {
            get {
                return ResourceManager.GetString("App_ExceptionMessageDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string App_ExceptionMessageDefaultMessage {
            get {
                return ResourceManager.GetString("App_ExceptionMessageDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ExceptionMessageHeader {
            get {
                return ResourceManager.GetString("ExceptionMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred in the application. Below is the available debug information for the current user level in the Carrot Framework..
        /// </summary>
        public static string ExceptionMessageInfo {
            get {
                return ResourceManager.GetString("ExceptionMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to run {0}.
        /// </summary>
        public static string File_ErrorLaunchingFile {
            get {
                return ResourceManager.GetString("File_ErrorLaunchingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be found: {0}.
        /// </summary>
        public static string File_FileNotFound {
            get {
                return ResourceManager.GetString("File_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string File_FileNotFoundHeader {
            get {
                return ResourceManager.GetString("File_FileNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found.
        /// </summary>
        public static string File_LocationNotFound {
            get {
                return ResourceManager.GetString("File_LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory could not be opened.
        /// </summary>
        public static string File_OpenLocationError {
            get {
                return ResourceManager.GetString("File_OpenLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory error.
        /// </summary>
        public static string File_OpenLocationErrorHeader {
            get {
                return ResourceManager.GetString("File_OpenLocationErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key could not be opened.
        /// </summary>
        public static string File_OpenRegKeyError {
            get {
                return ResourceManager.GetString("File_OpenRegKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening key.
        /// </summary>
        public static string File_OpenRegKeyErrorHeader {
            get {
                return ResourceManager.GetString("File_OpenRegKeyErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry key was not found.
        /// </summary>
        public static string File_RegKeyNotFound {
            get {
                return ResourceManager.GetString("File_RegKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key not found.
        /// </summary>
        public static string File_RegKeyNotFoundHeader {
            get {
                return ResourceManager.GetString("File_RegKeyNotFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string MessageHeader_Error {
            get {
                return ResourceManager.GetString("MessageHeader_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Message.
        /// </summary>
        public static string MessageHeader_Generic {
            get {
                return ResourceManager.GetString("MessageHeader_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Message.
        /// </summary>
        public static string MessageHeader_Information {
            get {
                return ResourceManager.GetString("MessageHeader_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Message.
        /// </summary>
        public static string MessageHeader_Question {
            get {
                return ResourceManager.GetString("MessageHeader_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Message.
        /// </summary>
        public static string MessageHeader_Success {
            get {
                return ResourceManager.GetString("MessageHeader_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message.
        /// </summary>
        public static string MessageHeader_Warning {
            get {
                return ResourceManager.GetString("MessageHeader_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information from the server was not valid.
        /// </summary>
        public static string Update_FormatError {
            get {
                return ResourceManager.GetString("Update_FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while connecting to the server.
        /// </summary>
        public static string Update_GenericError {
            get {
                return ResourceManager.GetString("Update_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server manifest could not be read.
        /// </summary>
        public static string Update_ManifestError {
            get {
                return ResourceManager.GetString("Update_ManifestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting news.
        /// </summary>
        public static string Update_NewsError {
            get {
                return ResourceManager.GetString("Update_NewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updater could not be launched. To manually download the new version, go to {0} and download the latest version from there..
        /// </summary>
        public static string Update_RunningUpdaterError {
            get {
                return ResourceManager.GetString("Update_RunningUpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running updater.
        /// </summary>
        public static string Update_RunningUpdaterErrorHeader {
            get {
                return ResourceManager.GetString("Update_RunningUpdaterErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Update_UnknownError {
            get {
                return ResourceManager.GetString("Update_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updater could not be created. To manually download the new version, go to {0} and download the latest version from there..
        /// </summary>
        public static string Update_UpdaterError {
            get {
                return ResourceManager.GetString("Update_UpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating updater.
        /// </summary>
        public static string Update_UpdaterErrorHeader {
            get {
                return ResourceManager.GetString("Update_UpdaterErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection could not be established to the server.
        /// </summary>
        public static string Update_WebError {
            get {
                return ResourceManager.GetString("Update_WebError", resourceCulture);
            }
        }
    }
}
