//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayCarrot.RCP.Metro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstallerGames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallerGames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayCarrot.RCP.Metro.Installer.Games.InstallerGames", typeof(InstallerGames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data
        ///Dll
        ///GXSetup.exe
        /// Leeme.txt
        /// Leggimi.txt
        /// Liesmich.txt
        /// Lisezmoi.txt
        /// Manual
        ///RAYMAN2.ICD
        ///Rayman2.exe
        ///Rayman2.ico
        /// Readme.txt
        ///Data\Game.dsb
        ///Data\Textures.cnt
        ///Data\Vignette.cnt
        ///Data\World
        ///Data\World\Levels
        ///Data\World\Sound
        ///Data\World\Levels\ANIMS0.DAT
        ///Data\World\Levels\ANIMS1.DAT
        ///Data\World\Levels\ANIMS2.DAT
        ///Data\World\Levels\Astro_00
        ///Data\World\Levels\Astro_10
        ///Data\World\Levels\Ball
        ///Data\World\Levels\Bast_09
        ///Data\World\Levels\Bast_10
        ///Data\World\Levels\Bast_20
        ///Data\World\Levels\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rayman2 {
            get {
                return ResourceManager.GetString("Rayman2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Licensfr.txt
        /// Licenssp.txt
        /// Licensuk.txt
        /// readmefr.txt
        /// readmesp.txt
        /// readmeuk.txt
        ///DX8_LOC
        ///FishBin
        ///MenuBin
        ///Videos
        ///TribeBin
        ///RM_Setup_DX8.exe
        ///R_Arena.exe
        ///R_Arena.ico
        ///MSVCP60.DLL
        ///binkw32.dll
        ///cfgmgr32.dll
        ///stlport_vc6.4.1.b6.dll
        /// DX8_LOC\DX8_English.ini
        /// DX8_LOC\DX8_French.ini
        /// DX8_LOC\DX8_Spanish.ini
        ///FishBin\1Shadow
        ///FishBin\1Shrine
        ///FishBin\1Sunset
        ///FishBin\2Haunted
        ///FishBin\2Palm
        ///FishBin\2Timber
        ///FishBin\3Coconut
        ///FishBin\3Ly
        ///FishBin\3Spell
        ///FishBin\4Forgot
        ///FishBin\4Gem
        ///FishBin\4Ghas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RaymanArena {
            get {
                return ResourceManager.GetString("RaymanArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Licensda.txt
        /// Licensfr.txt
        /// Licensge.txt
        /// Licensgl.txt
        /// Licensit.txt
        /// Licenssp.txt
        /// Licensuk.txt
        /// MSVCP60.DLL
        /// stlport_vc6.4.1.b6.dll
        /// Manual
        /// Manual\Rayman M FR.pdf
        /// Manual\Rayman M GER.pdf
        /// Manual\Rayman M IT.pdf
        /// Manual\Rayman M NL.pdf
        /// Manual\Rayman M SP.pdf
        /// Manual\Rayman M Scand.pdf
        /// Manual\Rayman M UK.pdf
        /// readmeda.txt
        /// readmefi.txt
        /// readmefr.txt
        /// readmege.txt
        /// readmeit.txt
        /// readmeno.txt
        /// readmesp.txt
        /// readmesw.txt
        /// readmeuk.txt
        ///DX8_LOC
        ///FishBin
        ///MenuBin
        ///Videos
        ///TribeBin
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RaymanM {
            get {
                return ResourceManager.GetString("RaymanM", resourceCulture);
            }
        }
    }
}
