//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayCarrot.RCP.Metro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayCarrot.RCP.Metro.Files.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_controller {
            get {
                object obj = ResourceManager.GetObject("dinput_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_mapping {
            get {
                object obj = ResourceManager.GetObject("dinput_mapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput8_controller {
            get {
                object obj = ResourceManager.GetObject("dinput8_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GXSetup_GOG {
            get {
                object obj = ResourceManager.GetObject("GXSetup_GOG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Rayman_Control_Panel_Updater {
            get {
                object obj = ResourceManager.GetObject("Rayman_Control_Panel_Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Rayman2_GOG {
            get {
                object obj = ResourceManager.GetObject("Rayman2_GOG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic\boss\foodworld\sampledemo_bossfo.isc
        ///cinematic\faery\faeryfree\background.isc
        ///cinematic\faery\faeryfree\fo_faeryfreescene.isc
        ///cinematic\faery\faeryfree\ju_faeryfreescene.isc
        ///cinematic\faery\faeryfree\mo_faeryfreescene.isc
        ///cinematic\faery\faeryfree\mu_faeryfreescene.isc
        ///cinematic\faery\faeryfree\oc_faeryfreescene.isc
        ///cinematic\levelending\levelending.isc
        ///cinematic\levelending\levelending_graph.isc
        ///scene\menus\inputconfiguration\inputconfiguration.isc
        ///scene\menus\mainmenu\menuback.isc
        ///sce [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RO_Levels {
            get {
                return ResourceManager.GetString("RO_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Rayman2]
        ///GLI_Mode = 1 - 640 x 480 x 16
        ///Language =English
        ///GLI_DllFile = GliDX6
        ///GLI_Dll = DirectX6
        ///GLI_Driver = display
        ///GLI_Device = Direct3D HAL
        ///ParticuleRate = High.
        /// </summary>
        public static string ubi {
            get {
                return ResourceManager.GetString("ubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----   Version 4.1.0 - March ?, 2019   -----
        ///
        ///• The program has been translated to Swedish, thus now allowing the language to be selected in the settings
        ///• The option to move existing backups has been readded when changing the backup location
        ///• Reorganized the settings page
        ///• Updates to the Carrot Framework and WPF implementation
        ///• Increased ToolTip timeout on InfoIcons
        ///• Minor bug fixes
        ///
        ///
        ///-----   Version 4.0.1 - March 15, 2019   -----
        ///
        ///• Updated the about page
        ///• Updated the help page
        ///• Chang [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
    }
}
