//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayCarrot.RCP.Metro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayCarrot.RCP.Metro.Files.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AdminWorker {
            get {
                object obj = ResourceManager.GetObject("AdminWorker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_controller {
            get {
                object obj = ResourceManager.GetObject("dinput_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_mapping {
            get {
                object obj = ResourceManager.GetObject("dinput_mapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput8_controller {
            get {
                object obj = ResourceManager.GetObject("dinput8_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LocalUtilities&quot;: {
        ///    &quot;Rayman1&quot;: [
        ///      &quot;R1TPLSUtility&quot;,
        ///      &quot;R1CompleteSoundtrackUtility&quot;,
        ///      &quot;R1FixConfigUtility&quot;
        ///    ],
        ///    &quot;RaymanDesigner&quot;: [
        ///      &quot;RDReplaceFilesUtility&quot;,
        ///      &quot;RDCreateConfigUtility&quot;
        ///    ],
        ///    &quot;Rayman2&quot;: [
        ///      &quot;R2CNTExplorerUtility&quot;,
        ///      &quot;R2GameSyncTextureInfoUtility&quot;,
        ///      &quot;R2RemoveDRMUtility&quot;,
        ///      &quot;R2DiscPatchUtility&quot;,
        ///      &quot;R2TranslationUtility&quot;
        ///    ],
        ///    &quot;Demo_Rayman2_1&quot;: [
        ///      &quot;R2Demo1CNTExplorerUtility&quot;
        ///    ],
        ///    &quot;Demo_Rayman2_2&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GXSetup_GOG {
            get {
                object obj = ResourceManager.GetObject("GXSetup_GOG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Bast_10.sna&quot;: [
        ///    1228515,
        ///    1233843
        ///  ],
        ///  &quot;Bast_20.sna&quot;: [
        ///    1025823,
        ///    1031151
        ///  ],
        ///  &quot;Boat02.sna&quot;: [
        ///    742395,
        ///    746115
        ///  ],
        ///  &quot;Cask_10.sna&quot;: [
        ///    725591,
        ///    730919
        ///  ],
        ///  &quot;Chase_10.sna&quot;: [
        ///    963751,
        ///    969079
        ///  ],
        ///  &quot;Earth_10.sna&quot;: [
        ///    942267
        ///  ],
        ///  &quot;Earth_20.sna&quot;: [
        ///    553827
        ///  ],
        ///  &quot;Earth_30.sna&quot;: [
        ///    592195
        ///  ],
        ///  &quot;GLob_10.sna&quot;: [
        ///    915843,
        ///    921171
        ///  ],
        ///  &quot;GLob_20.sna&quot;: [
        ///    880327,
        ///    885655
        ///  ],
        ///  &quot;GLob_30.sna&quot;: [
        ///    302315, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string R2_Sna_Drm_Offsets {
            get {
                return ResourceManager.GetString("R2_Sna_Drm_Offsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RAYMAN {
            get {
                object obj = ResourceManager.GetObject("RAYMAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Rayman_Control_Panel_Updater {
            get {
                object obj = ResourceManager.GetObject("Rayman_Control_Panel_Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Rayman2_GOG {
            get {
                object obj = ResourceManager.GetObject("Rayman2_GOG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic\darkt_bosses\darkt_boss_ending_moon_cine.isc
        ///cinematic_retro\boss\foodworld\sampledemo_bossfo.isc
        ///enginedata\defaultloadingscreen\defaultblackscreen.isc
        ///enginedata\defaultloadingscreen\defaultloadingscreen.isc
        ///enginedata\defaultloadingscreen\logo_rl_mainmenu.isc
        ///enginedata\defaultloadingscreen\interactiveloadingscreen\babeltower_rl\loading_babeltower.isc
        ///enginedata\defaultloadingscreen\interactiveloadingscreen\babeltower_rl\score_recap_babeltower.isc
        ///enginedata\defaultloadingscreen\interact [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RL_Levels {
            get {
                return ResourceManager.GetString("RL_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinematic\boss\foodworld\sampledemo_bossfo.isc
        ///cinematic\faery\faeryfree\background.isc
        ///cinematic\faery\faeryfree\fo_faeryfreescene.isc
        ///cinematic\faery\faeryfree\ju_faeryfreescene.isc
        ///cinematic\faery\faeryfree\mo_faeryfreescene.isc
        ///cinematic\faery\faeryfree\mu_faeryfreescene.isc
        ///cinematic\faery\faeryfree\oc_faeryfreescene.isc
        ///cinematic\levelending\levelending.isc
        ///cinematic\levelending\levelending_graph.isc
        ///scene\menus\inputconfiguration\inputconfiguration.isc
        ///scene\menus\mainmenu\menuback.isc
        ///sce [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RO_Levels {
            get {
                return ResourceManager.GetString("RO_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Rayman2]
        ///GLI_Mode = 1 - 640 x 480 x 16
        ///Language =English
        ///GLI_DllFile = GliDX6
        ///GLI_Dll = DirectX6
        ///GLI_Driver = display
        ///GLI_Device = Direct3D HAL
        ///ParticuleRate = High.
        /// </summary>
        public static string ubi {
            get {
                return ResourceManager.GetString("ubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Uninstaller {
            get {
                object obj = ResourceManager.GetObject("Uninstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----   Version 9.3.0 - February ??, 2020   -----
        ///• Added the decoder utilities category
        ///• The Rayman 2 DRM removal patch can now be applied again if already applied without first reverting it
        ///• Updated libraries
        ///• Changed the icon for the convert utilities tab
        ///
        ///
        ///-----   Version 9.2.4 - February 2, 2020   -----
        ///• Added the utility for synchronizing the OpenSpace texture resolution to the game specific utilities sections
        ///• Changed the order of the Archive Explorer utilities
        ///
        ///
        ///-----   Version 9.2. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
    }
}
