//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayCarrot.RCP.Metro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayCarrot.RCP.Metro.Files.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known issues:
        ///- Rayman 2 button button mapping text box does not allow modifier keys (Ctrl, Shift, Win or Alt)
        ///- The installer window is laggy
        ///
        ///Unfinished features:
        ///
        ///- Add control tool tips
        ///- About page
        ///
        ///- Configuration dialogs for:
        ///-- Rayman M/Arena
        ///-- Rayman 3
        ///-- Rayman Raving Rabbids
        ///-- Rayman Origins
        ///-- Rayman Legends
        ///
        ///- Port utilities:
        ///-- R1 PlayStation soundtrack (checkbox in config to launch in this mode)
        ///-- Replace Rayman Forever incomplete soundtrack (checkbox in config, disabled  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_controller {
            get {
                object obj = ResourceManager.GetObject("dinput_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput_mapping {
            get {
                object obj = ResourceManager.GetObject("dinput_mapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] dinput8_controller {
            get {
                object obj = ResourceManager.GetObject("dinput8_controller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----   Version 4.0.0 - March ? 2019   -----
        ///
        ///• Windows Vista or higher is required to run the application
        ///• Updated the program to use WPF instead of WinForms
        ///• Changed the theme to Metro theme with dark/light modes
        ///• Simplified game selection and utilities
        ///• Common DosBox commands can now be set using the new DosBox configuration dialog
        ///
        ///Other changes:
        ///• Rayman M/Arena are now treated as separate games
        ///• Rayman 2 utilities have been integrated into its configuration dialog. It now also shows the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
    }
}
