namespace RayCarrot.RCP.Metro;

public enum GenericIconKind
{
    None,

    GameAction_Play,
    GameAction_RunAsAdmin,
    GameAction_Location,
    GameAction_Web,
    GameAction_Steam,
    GameAction_Microsoft,

    GameFeature_Archive,
    GameFeature_Config,
    GameFeature_Progression,
    GameFeature_Utilities,
    GameFeature_ModLoader,
    GameFeature_PrototypeRestoration,
    GameFeature_RuntimeModification,

    GamePanel_Archive,
    GamePanel_ModLoader,
    GamePanel_Progression,
    GamePanel_PrototypeRestoration,
    GamePanel_RuntimeModification,

    GameAdd_Locate,
    GameAdd_DiscInstall,
    GameAdd_Download,
    GameAdd_Purchase,

    GameOptions_Config,
    GameOptions_GameClient,
    GameOptions_Utilities,

    SetupGame_Mod,
    SetupGame_Config,
    SetupGame_GameClient,
    SetupGame_FileReplacement,
    SetupGame_Fix,
    SetupGame_Download,

    Settings_Language,
    Settings_UserLevel,
    Settings_General,
    Settings_Design,
    Settings_Startup,
    Settings_Files,
    Settings_WindowsIntegration,
    Settings_Progression,
    Settings_ArchiveExplorer,
    Settings_ModLoader,
    Settings_Debug,

    Window_ArchiveExplorer,
    Window_ArchiveCreator,
    Window_ModLoader,
    Window_ModCreator,
    Window_GameOptions,
    Window_Installer,
    Window_Downloader,
    Window_DriveSelection,
    Window_ItemSelection,
    Window_GamesSelection,
    Window_JumpListEdit,
    Window_DialogMessage,
    Window_StringInput,
    Window_ProgramSelection,
    Window_AppNews,
    Window_AddGames,
    Window_GameClientsSetup,
    Window_GameDebug,
    Window_GameClientDebug,
    Window_AnniversaryUpdate,
    Window_PrototypeRestoration,
    Window_RuntimeModifications,

    Utilities_Rayman1_TPLS,
    Utilities_ArchiveExplorer,
    Utilities_Ray1Editor,
    Utilities_R1PasswordGenerator,
    Utilities_Converters,
    Utilities_Decoders,
    Utilities_Serializers,
}